### ISSUE TITLE
Create a webform to directly push the inputs to the OpenStreetMap API

### ISSUE THREAD

**Issue by chnuessli** [loleg/dinacon-hacknight#2]
# Form on a webpage that serves an API

Hello, absolute programming beginner here. I'm the founder of defikarte.ch where you can report defibrillators seen on the street. Right now, the report button is just a mailto: link to my mailbox. It would be nice if there was a form that directly pushes to the OSM API.

## OSM API
[OSM API Wiki](https://wiki.openstreetmap.org/wiki/API_v0.6)

## Get involved

Get involved in two open source projects, the world's largest geospatial wiki (openstreetmap) and the defibrillator in switzerlands only map that should suit them all.
Repo here: [https://github.com/chnuessli/defikarte.ch](https://github.com/chnuessli/defikarte.ch)

#1 can you solve this challenge with a beginner? 👍🏼 i'd love to code with you

**Comment by loleg** [comment]
We are now working on this at https://hacknight.dinacon.ch/project/43

**Comment by chnuessli** [comment]
Closing this, i transfer it to my Repo. The issue wasn't done on Hacknight :)

**Comment by loleg** [comment]
Another Hacknight coming up - feel free to Reopen or pitch us another challenge!
