### ISSUE TITLE
Promote open hardware and join the MakeZurich kickoff

### ISSUE THREAD

**Issue by loleg** [loleg/dinacon-hacknight#4]
Today at 18:00 we kick-off MakeZurich 2020 from the comfort of our sofa / hack-corner! They have been well received at past conferences, e.g. receiving an [Open Internet Award](https://www.thethingsnetwork.org/community/zentralschweiz/post/open-network-infrastructure-association-erhalt-dinacon-open-internet-award) in 2017. 

We can spread the word about this week-long event in the DINAcon community, for example with a shortlist of cool crowd-sensing and crowd-science projects currently going on in Switzerland, to which people could contribute some hands-on time or hands-off money.

See https://makezurich.ch

**Comment by loleg** [comment]
@gonzalocasas @tamberg what do you think?

**Comment by gonzalocasas** [comment]
💯  sounds great! [LogAir](https://logair.github.io/)  is one such project, and it's also one of the challenges of this year

**Comment by loleg** [comment]
@gonzalocasas feel free to open a fresh issue if there's something (TS v3?) we should hack on next month!
